development:
  adapter: redis
  url: redis://127.0.0.1:6379

test:
  adapter: redis

production:
  adapter: redis
  url: redis://redistogo:7422704fe5713fee9258a6632b1b6f74@pearlfish.redistogo.com:10027/
  # channel_prefix: arduino-webserver_production
