development:
  adapter: redis
  url: redis://127.0.0.1:6379

test:
  adapter: redis

production:
  adapter: redis
  url: redis://redistogo:1d85576e6641ef682dfc1748ae7a94f5@tarpon.redistogo.com:11818/
  
  # channel_prefix: arduino-webserver_production
